from fastapi import FastAPI
from pydantic import BaseModel
from utils.ml_engine import run_ai_analysis
from utils.ela_analyzer import run_ela_analysis  # Import our new tool!

app = FastAPI()

class ImageRequest(BaseModel):
    image_url: str

@app.post("/analyze-image")
async def analyze_image(req: ImageRequest):
    print(f"\n--- New Scan Request ---")
    
    # 1. Run the Neural Network (Deepfake check)
    ai_result = run_ai_analysis(req.image_url)
    
    # 2. Run Error Level Analysis (Photoshop/Splicing check)
    ela_flag = run_ela_analysis(req.image_url)
    
    # 3. Combine the Forensic Flags
    # We take the flags generated by the AI and add our new ELA flag to the list
    combined_forensics = ai_result["forensics_flags"]
    combined_forensics.append(ela_flag)
    
    # Optional: If ELA detects tampering, force the label to at least 'suspicious'
    final_label = ai_result["label"]
    if "Anomaly Detected" in ela_flag and final_label == "authentic":
        final_label = "suspicious"
        ai_result["reason"] += " However, Error Level Analysis detected potential splicing."

    return {
        "url": req.image_url,
        "label": final_label,
        "confidence": ai_result["confidence"],
        "reason": ai_result["reason"],
        "forensics": combined_forensics  # Send the combined list to the React UI
    }